from django.urls import path
from home.views import (
    home,
    about_us,
    contact_us,
    item_detail,
    search_filter,
    check_out,
    cart,
    upi_pay,
    card_pay,
    thank,
    my_collections,
    create_collection,
    delete_collecton,
    list_collections,
    view_collection,
    variant_detail,
    remove_from_cart,
    Wishlist,
    remove_from_wishlist,
    add_to_wishlist
)

urlpatterns = [
    path("", home, name="home"),
    path("about-us/", about_us, name="about-us"),
    path("contact-us/", contact_us, name="contact-us"),
    path("item-detail/<pk>/", item_detail, name="item-detail"),
    path("variant-detail/<pk>/", variant_detail, name="variant-detail"),
    path("search/", search_filter, name="search"),
    path("check-out/", check_out, name="check-out"),
    path("my-cart/", cart, name="my-cart"),
    path("upi-gateway/", upi_pay, name="upi-gateway"),
    path("card-gateway/", card_pay, name="card-gateway"),
    path("thank-you/", thank, name="thank-you"),
    path("manage-collections/", my_collections, name="manage-collections"),
    path("create-collection/", create_collection, name="create-collection"),
    path("delete-collection/<pk>", delete_collecton, name="delete-collection"),
    path("list-collections/", list_collections, name="list-collections"),
    path("view-collection/<pk>", view_collection, name="view-collection"),
    path("remove/<pk>", remove_from_cart, name="remove"),
    path("wishlist/", Wishlist, name="wishlist"),
    path("remove-w/<pk>", remove_from_wishlist, name="remove-w"),
    path("add-to-wishlist/<pk>", add_to_wishlist, name="add-to-wishlist"),
]
