# Generated by Django 5.2.1 on 2025-05-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_created_at_remove_address_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller'},
        ),
    ]
