# Generated by Django 5.2.1 on 2025-05-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_options_alter_seller_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='is_seller',
            field=models.BooleanField(default=True),
        ),
    ]
