# Generated by Django 5.2.1 on 2025-05-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_is_seller_seller_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_name',
            new_name='Colony',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_number',
            new_name='nearby_place',
        ),
    ]
