# Generated by Django 5.2.1 on 2025-05-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_street_name_address_colony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('USA', 'USA'), ('China', 'China'), ('Russia', 'Russia')], default='India', max_length=100),
        ),
    ]
