# Generated by Django 5.2.1 on 2025-05-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_address_id_remove_seller_address_address_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='Colony',
            new_name='colony',
        ),
    ]
