# Generated by Django 5.2.1 on 2025-05-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_colony_address_colony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_seller',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
