# Generated by Django 5.2.1 on 2025-05-29 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customer_is_seller_alter_seller_is_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='company_name',
            new_name='bmp_id',
        ),
        migrations.AddField(
            model_name='seller',
            name='is_varified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='accounts.address'),
        ),
    ]
