# Generated by Django 5.2.1 on 2025-05-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_company_name_seller_bmp_id_seller_is_varified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='business_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
