# Generated by Django 5.2.1 on 2025-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_address_house_number_seller_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bmp_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='gst_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
