# Generated by Django 5.2.1 on 2025-05-16 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catagorie'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='images',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='status',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.UUID('43a89e8b-00a0-4997-b94b-ed1ec308ba0c')),
        ),
    ]
