# Generated by Django 5.2.1 on 2025-06-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='home.item'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='items',
            field=models.ManyToManyField(related_name='wishlist', to='home.item'),
        ),
    ]
