# Generated by Django 5.2.1 on 2025-05-16 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_options_alter_brand_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e59e8ed1-74d3-45ab-a345-b5197d549337'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
