# Generated by Django 5.2.1 on 2025-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_icon',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
