# Generated by Django 5.2.1 on 2025-06-10 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostSearched',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search', models.CharField(max_length=225)),
                ('times_searched', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
