# Generated by Django 5.2.1 on 2025-05-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_keyfeatures_item_item_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catagory_logo_of', to='home.images'),
        ),
        migrations.AddField(
            model_name='collection',
            name='collection_logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_logo_of', to='home.images'),
        ),
    ]
