# Generated by Django 5.2.1 on 2025-06-12 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_mostsearched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_in_orders', to='home.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.customerorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
