# Generated by Django 5.2.1 on 2025-05-20 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_category_category_logo_collection_collection_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
