# Generated by Django 5.2.1 on 2025-05-26 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_brand_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_catagory_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catagory_sub', to='home.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
