# Generated by Django 5.2.1 on 2025-05-26 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('quantity_unit', models.CharField(default='kg', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='quantitybundle',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_bundels',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_features',
        ),
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='item',
            name='sku_name',
            field=models.CharField(default='no sku', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_items', to='home.brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='home.subcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantity_item', to='home.quantity'),
        ),
        migrations.DeleteModel(
            name='QuantityUnit',
        ),
        migrations.DeleteModel(
            name='QuantityBundle',
        ),
    ]
