# Generated by Django 5.2.1 on 2025-05-27 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_quantity_remove_quantitybundle_quantity_unit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyFeatures',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='quantity',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_quantities', to='home.item'),
            preserve_default=False,
        ),
    ]
