# Generated by Django 5.2.1 on 2025-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_delete_keyfeatures_remove_item_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='item',
        ),
        migrations.AddField(
            model_name='quantity',
            name='item',
            field=models.ManyToManyField(related_name='item_quantities', to='home.item'),
        ),
    ]
