# Generated by Django 5.2.1 on 2025-05-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_quantity_item_quantity_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sku_name',
            new_name='sku',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_logo',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_logo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_images',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='quantity_unit',
        ),
        migrations.AddField(
            model_name='images',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='home.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
    ]
