# Generated by Django 5.2.1 on 2025-05-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_sku_name_item_sku_remove_brand_brand_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='item',
        ),
        migrations.AddField(
            model_name='quantity',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_quantities', to='home.item'),
            preserve_default=False,
        ),
    ]
