# Generated by Django 5.2.1 on 2025-05-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_quantity_item_quantity_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_Brand',
            new_name='item_brand',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_discount_persentage',
            new_name='item_discount_percentage',
        ),
    ]
