# Generated by Django 5.2.1 on 2025-05-27 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_brand_brand_alter_category_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='image_item', to='home.images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VariantItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_name', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.FloatField(default=1)),
                ('sku', models.CharField(default='no sku', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='home.item')),
                ('item_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_item_varient', to='home.images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
