# Generated by Django 5.2.1 on 2025-05-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_category_options_customerorder_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantitem',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
