# Generated by Django 5.2.1 on 2025-05-28 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_variantitem_discount_percentage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantitem',
            unique_together=set(),
        ),
    ]
