# Generated by Django 5.2.1 on 2025-05-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_seller_bmp_id_alter_seller_gst_number_and_more'),
        ('home', '0024_alter_variantitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_collections', to='accounts.seller'),
            preserve_default=False,
        ),
    ]
