# Generated by Django 5.2.1 on 2025-06-01 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_collection_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_category',
            new_name='item_subcategory',
        ),
    ]
