# Generated by Django 5.2.1 on 2025-06-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_item_category_item_item_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
