# Generated by Django 5.2.1 on 2025-06-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_collection_collection_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='images',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=10),
        ),
    ]
